# Generated by Django 5.1.15 on 2026-09-07 06:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='название')),
                ('slug', models.SlugField(unique=True, verbose_name='слаг')),
                ('site_url', models.URLField(blank=True, verbose_name='URL сайта')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True, verbose_name='хеш токена')),
                ('template', models.TextField(blank=True, help_text='Django-шаблон. Переменные: project, fields, created_at, source', verbose_name='шаблон сообщения')),
                ('buttons_enabled', models.BooleanField(default=True, verbose_name='кнопки статусов')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'проект',
                'verbose_name_plural': 'проекты',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Recipient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='chat_id')),
                ('kind', models.CharField(choices=[('private', 'Личный чат'), ('group', 'Группа')], default='private', max_length=10, verbose_name='тип')),
                ('title', models.CharField(blank=True, max_length=255, verbose_name='название')),
                ('is_admin', models.BooleanField(default=False, verbose_name='администратор')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
            ],
            options={
                'verbose_name': 'получатель',
                'verbose_name_plural': 'получатели',
                'ordering': ['title'],
            },
        ),
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payload', models.JSONField(verbose_name='данные')),
                ('rendered_text', models.TextField(verbose_name='отправленный текст')),
                ('source', models.CharField(blank=True, max_length=200, verbose_name='источник')),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('done', 'Обработана')], default='new', max_length=20, verbose_name='статус')),
                ('idempotency_key', models.CharField(blank=True, db_index=True, max_length=255, verbose_name='ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создана')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='notifier.project', verbose_name='проект')),
            ],
            options={
                'verbose_name': 'заявка',
                'verbose_name_plural': 'заявки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='активна')),
                ('subscribed_at', models.DateTimeField(auto_now_add=True, verbose_name='подключён')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='notifier.project', verbose_name='проект')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subscriptions', to='notifier.recipient', verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'подписка',
                'verbose_name_plural': 'подписки',
                'unique_together': {('project', 'recipient')},
            },
        ),
    ]
