# Generated by Django 5.1.15 on 2026-09-07 06:55

import django.db.models.deletion
import notifier.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invite',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(default=notifier.models.generate_invite_code, max_length=20, unique=True, verbose_name='код')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='истекает')),
                ('is_multi_use', models.BooleanField(default=False, verbose_name='многоразовый')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='дата использования')),
                ('is_active', models.BooleanField(default=True, verbose_name='активен')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='создан')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='invites', to='notifier.project', verbose_name='проект')),
                ('used_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='used_invites', to='notifier.recipient', verbose_name='использован')),
            ],
            options={
                'verbose_name': 'код приглашения',
                'verbose_name_plural': 'коды приглашений',
                'ordering': ['-created_at'],
            },
        ),
    ]
