# Generated by Django 5.1.15 on 2026-09-07 07:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifier', '0002_invite'),
    ]

    operations = [
        migrations.CreateModel(
            name='Delivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message_id', models.BigIntegerField(blank=True, null=True, verbose_name='message_id')),
                ('ok', models.BooleanField(default=False, verbose_name='доставлено')),
                ('error', models.TextField(blank=True, verbose_name='ошибка')),
                ('sent_at', models.DateTimeField(auto_now_add=True, verbose_name='отправлено')),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifier.lead', verbose_name='заявка')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='notifier.recipient', verbose_name='получатель')),
            ],
            options={
                'verbose_name': 'доставка',
                'verbose_name_plural': 'доставки',
                'ordering': ['-sent_at'],
            },
        ),
    ]
